"""empty message

Revision ID: 02609b9035c1
Revises: 
Create Date: 2025-07-23 03:06:02.291658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02609b9035c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('razas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellido', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('especie', sa.String(length=30), nullable=False),
    sa.Column('foto', sa.String(length=300), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('raza', sa.String(length=300), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raza_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raza_id'], ['razas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('alergias', sa.String(length=300), nullable=True),
    sa.Column('condiciones_previas', sa.String(length=500), nullable=True),
    sa.Column('medicamentos_actuales', sa.String(length=250), nullable=True),
    sa.Column('esterilizado', sa.Boolean(), nullable=False),
    sa.Column('fecha_ultima_revision', sa.Date(), nullable=True),
    sa.Column('veterinario_habitual', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=800), nullable=True),
    sa.Column('grupo_sanguineo', sa.String(length=20), nullable=True),
    sa.Column('microchip', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id')
    )
    op.create_table('recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=500), nullable=False),
    sa.Column('respuesta', sa.String(length=2000), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacunas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacunas')
    op.drop_table('recomendaciones')
    op.drop_table('medical_profiles')
    op.drop_table('pets')
    op.drop_table('favorites')
    op.drop_table('users')
    op.drop_table('razas')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
