"""empty message

Revision ID: 151205ab4aa4
Revises: a5c3312e316e
Create Date: 2025-07-21 23:08:17.794979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151205ab4aa4'
down_revision = 'a5c3312e316e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pesos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('pesos_pet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pesos_pkey'))
    )
    # ### end Alembic commands ###
