"""empty message

Revision ID: 205714e76d4a
Revises: e259a35f9639
Create Date: 2025-07-22 02:26:43.846065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205714e76d4a'
down_revision = 'e259a35f9639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pets', schema=None) as batch_op:
     batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    op.drop_table('contact_messages')
    # ### end Alembic commands ###
