"""empty message

Revision ID: 297da670398b
Revises: ad1b4b1fed07
Create Date: 2025-07-21 22:28:14.535232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297da670398b'
down_revision = 'ad1b4b1fed07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_history')
    # ### end Alembic commands ###
