"""empty message

Revision ID: 340ac959fc49
Revises: 6540655a8479
Create Date: 2025-07-24 01:32:24.617348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340ac959fc49'
down_revision = '6540655a8479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacunas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vacunas_mascota_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pets', ['mascota_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacunas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vacunas_mascota_id_fkey'), 'pets', ['mascota_id'], ['id'])

    # ### end Alembic commands ###
