"""empty message

Revision ID: 3575181b6c58
Revises: a23dcd5f67ed
Create Date: 2025-07-20 22:32:36.456376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3575181b6c58'
down_revision = 'a23dcd5f67ed'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('vacunas', schema=None) as batch_op:
        # Solo cambia nullable, ¡NO vuelvas a crear la FK!
        batch_op.alter_column('mascota_id', nullable=False)

        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacunas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mascota_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vacunas_mascota_id_fkey'), 'pets', ['mascota_id'], ['id'])
        batch_op.drop_column('pet_id')

    # ### end Alembic commands ###
