"""empty message

Revision ID: 6540655a8479
Revises: db5761325a20
Create Date: 2025-07-24 01:29:23.232516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6540655a8479'
down_revision = 'db5761325a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['pet_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
