"""empty message

Revision ID: 6a4e76b14456
Revises: 224e98ff68f7
Create Date: 2025-07-17 00:08:29.513283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4e76b14456'
down_revision = '224e98ff68f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('sexo', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('sexo')
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###
