"""empty message

Revision ID: a23dcd5f67ed
Revises: c8a082cf479e
Create Date: 2025-07-20 22:08:12.390958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23dcd5f67ed'
down_revision = 'c8a082cf479e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('fecha_identificacion', sa.Date(), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivos_medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('resultado', sa.String(length=300), nullable=True),
    sa.Column('veterinario', sa.String(length=120), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_reproductivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('esterilizado', sa.Boolean(), nullable=True),
    sa.Column('fecha_esterilizacion', sa.Date(), nullable=True),
    sa.Column('fecha_ultimo_celo', sa.Date(), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('dosis', sa.String(length=80), nullable=True),
    sa.Column('frecuencia', sa.String(length=80), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_personales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.String(length=350), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problemas_salud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('fecha_identificacion', sa.Date(), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problemas_salud')
    op.drop_table('pesos')
    op.drop_table('notas_personales')
    op.drop_table('medicamentos')
    op.drop_table('estado_reproductivo')
    op.drop_table('consultas')
    op.drop_table('archivos_medicos')
    op.drop_table('alergias')
    # ### end Alembic commands ###
