"""empty message

Revision ID: ad1b4b1fed07
Revises: 3575181b6c58
Create Date: 2025-07-21 21:52:19.895709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1b4b1fed07'
down_revision = '3575181b6c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('alergias', sa.String(length=300), nullable=True),
    sa.Column('condiciones_previas', sa.String(length=500), nullable=True),
    sa.Column('medicamentos_actuales', sa.String(length=250), nullable=True),
    sa.Column('esterilizado', sa.Boolean(), nullable=False),
    sa.Column('fecha_ultima_revision', sa.Date(), nullable=True),
    sa.Column('veterinario_habitual', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=800), nullable=True),
    sa.Column('grupo_sanguineo', sa.String(length=20), nullable=True),
    sa.Column('microchip', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id')
    )
    op.drop_table('consultas')
    op.drop_table('pesos')
    op.drop_table('medicamentos')
    op.drop_table('problemas_salud')
    op.drop_table('alergias')
    op.drop_table('notas_personales')
    op.drop_table('archivos_medicos')
    op.drop_table('estado_reproductivo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_reproductivo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('esterilizado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_esterilizacion', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_ultimo_celo', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mascota_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], name=op.f('estado_reproductivo_mascota_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('estado_reproductivo_pkey'))
    )
    op.create_table('archivos_medicos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mascota_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], name=op.f('archivos_medicos_mascota_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('archivos_medicos_pkey'))
    )
    op.create_table('notas_personales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nota', sa.VARCHAR(length=350), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mascota_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], name=op.f('notas_personales_mascota_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notas_personales_pkey'))
    )
    op.create_table('alergias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('fecha_identificacion', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mascota_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], name=op.f('alergias_mascota_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alergias_pkey'))
    )
    op.create_table('problemas_salud',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('fecha_identificacion', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mascota_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], name=op.f('problemas_salud_mascota_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('problemas_salud_pkey'))
    )
    op.create_table('medicamentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('dosis', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('frecuencia', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('mascota_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], name=op.f('medicamentos_mascota_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('medicamentos_pkey'))
    )
    op.create_table('pesos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mascota_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], name=op.f('pesos_mascota_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pesos_pkey'))
    )
    op.create_table('consultas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('resultado', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('veterinario', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('mascota_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], name=op.f('consultas_mascota_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consultas_pkey'))
    )
    op.drop_table('medical_profiles')
    # ### end Alembic commands ###
