"""add Raza model and raza_id to Pet

Revision ID: afbba44c26d8
Revises: b3a88801125c
Create Date: 2025-07-09 04:44:18.062218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbba44c26d8'
down_revision = 'b3a88801125c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raza_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'razas', ['raza_id'], ['id'])
        batch_op.drop_column('raza')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raza', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('raza_id')

    op.drop_table('razas')
    # ### end Alembic commands ###
