"""add Vacuna model

Revision ID: b3a88801125c
Revises: f444e0d68526
Create Date: 2025-07-03 15:29:49.205073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a88801125c'
down_revision = 'f444e0d68526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacunas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacunas')
    # ### end Alembic commands ###
