"""empty message

Revision ID: c8a082cf479e
Revises: 6a4e76b14456
Create Date: 2025-07-17 01:22:14.536357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a082cf479e'
down_revision = '6a4e76b14456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=500), nullable=False),
    sa.Column('respuesta', sa.String(length=2000), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recomendaciones')
    # ### end Alembic commands ###
