"""empty message

Revision ID: db5761325a20
Revises: 02609b9035c1
Create Date: 2025-07-24 01:25:20.788473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5761325a20'
down_revision = '02609b9035c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('medical_profiles_pet_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('medical_profiles_pet_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pets', ['pet_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('medical_profiles_pet_id_fkey'), 'pets', ['pet_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('medical_profiles_pet_id_key'), ['pet_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
